# Generated by Django 4.1.1 on 2022-09-17 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=50, verbose_name="uuid")),
                ("name", models.CharField(max_length=256, verbose_name="Title")),
                ("movie_count", models.IntegerField(default=0, verbose_name="Count")),
            ],
        ),
        migrations.CreateModel(
            name="CollectionMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=50, verbose_name="uuid")),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "created_on",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Created On"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="genres", to="movies.moviegenre"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=50, verbose_name="uuid")),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "created_on",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Created On"
                    ),
                ),
                (
                    "movies",
                    models.ManyToManyField(
                        related_name="movies", to="movies.collectionmovie"
                    ),
                ),
            ],
        ),
    ]
