# Generated by Django 4.1.1 on 2022-09-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_collection_uuid_alter_collectionmovie_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_count",
                    models.IntegerField(default=0, verbose_name="Request Count"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="moviegenre",
            name="movie_count",
            field=models.IntegerField(default=1, verbose_name="Count"),
        ),
        migrations.AlterField(
            model_name="moviegenre",
            name="name",
            field=models.CharField(max_length=256, verbose_name="name"),
        ),
    ]
